FROM hashicorp/vault:1.17.2

LABEL org.opencontainers.image.description "This image contains vault for my Github Actions"
LABEL org.opencontainers.image.url https://github.com/obervinov/images/docker/vault
LABEL org.opencontainers.image.documentation https://github.com/obervinov/images/docker/vault/README.md
LABEL org.opencontainers.image.authors https://github.com/obervinov
LABEL org.opencontainers.image.source https://github.com/obervinov/images
LABEL org.opencontainers.image.version 1.17.2

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["server"]
