---
name: PR

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  pr:
    uses: obervinov/_templates/.github/workflows/pr.yaml@release/v2.1.0
  images:
    uses: obervinov/_templates/.github/workflows/images.yaml@release/v2.1.0
