---
name: PR

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  pr:
    uses: obervinov/_templates/.github/workflows/pr.yaml@v2.1.1
  images:
    uses: obervinov/_templates/.github/workflows/images.yaml@v2.1.1
