---
name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    uses: obervinov/_templates/.github/workflows/release.yaml@v2.0.2
  images:
    uses: obervinov/_templates/.github/workflows/images.yaml@v2.0.2
