---
name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  changelog:
    uses: obervinov/_templates/.github/workflows/changelog.yaml@v1.1.0

  readme:
    uses: obervinov/_templates/.github/workflows/readme.yaml@v1.1.0

  images:
    uses: obervinov/_templates/.github/workflows/images.yaml@v1.1.0

  create-release:
    uses: obervinov/_templates/.github/workflows/release.yaml@v1.1.0
    needs: [changelog, readme, images]
